FROM nginx:1.20.1-alpine AS runtime

COPY ./matomo.template.conf /matomo.template.conf

EXPOSE 8080

CMD envsubst '${MATOMO_HOST} ${MATOMO_INTERNAL_HOST}' < /matomo.template.conf > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'